title: Add a full width quote
hero_image: images/banner.png
description: Add a full width quote
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add a full width quote
